schema_version = "1.0.0"

# Toasters Blender Plugin Extension
id = "toasters_blender_plugin"
version = "5.2.32"
name = "Toasters Blender Plugin"
tagline = "Import and optimize 3D models easily into VRChat"
maintainer = "magictwin"
type = "add-on"
website = "https://github.com/magictwinsworld/Toasters-Blender-Plugin"
tags = ["Modeling", "Rigging"]
blender_version_min = "5.0.0"
license = [
  "SPDX:MIT",
]

[permissions]
files = "Access files for importing and exporting model assets"
network = "Access network for downloading translations and checking updates"

